# Constants for Simple Thermostat A
DOMAIN = "simple_thermostat_a"
CONF_HEATER = "heater"
CONF_NAME = "name"
CONF_SENSOR = "target_sensor"
CONF_AC_MODE = "ac_mode"
CONF_MAX_TEMP = "max_temp"
CONF_MIN_CYCLE_DURATION = "min_cycle_duration"
CONF_MIN_TEMP = "min_temp"
DEFAULT_MIN_CYCLE_DURATION = '00:00:00'
DEFAULT_NAME = "Simple Thermostat A"
CONF_HOT_TOLERANCE = "hot_tolerance"
DEFAULT_TOLERANCE = 0.3
CONF_COLD_TOLERANCE = "cold_tolerance"
CONF_TARGET_TEMP = "target_temp"
CONF_KEEP_ALIVE = "keep_alive"
CONF_INITIAL_HVAC_MODE = "initial_hvac_mode"
CONF_PRECISION = "precision"
CONF_UNIQUE_ID = "unique_id"
